version: "3.7"

services:

  postgres-service:
    container_name: postgres-service
    restart: always
    env_file: postgres.env
    build:
      context: ./postgres
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - ./storage/pgdata:/var/lib/postgresql/data

  rabbitmq-service:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-service
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - ./storage/rabbitmq/etc:/etc/rabbitmq
      - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
      - ./storage/rabbitmq/log/:/var/log/rabbitmq

  redis-service:
    image: "redis:latest"
    container_name: redis-service
    ports:
      - "6379:6379"
    #command: redis-server --requirepass yourpassword

  ldap-service:
    image: osixia/openldap:latest
    container_name: ldap-service
    env_file: ldap.env
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - "./storage/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom"
    command: ["/bin/sh", "-c", "/container/tool/run --copy-service -l debug"]

  pgadmin-service:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8090:80
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=doseok@madang.com
      - PGADMIN_DEFAULT_PASSWORD=kim7795004
volumes:
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage/pgdata  
  rabbitmq-etc: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage/rabbitmq/etc
  rabbitmq-data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage/rabbitmq/mnesia
  rabbitmq-logs: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage/rabbitmq/log
  www: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage/www
