version: "3.7"
services:
  rabbitmq-service:
    #image: rabbitmq:management-alpine
    container_name: rabbitmq-service
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      #- ./rabbitmq/etc:/etc/rabbitmq
      - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
      - ./storage/rabbitmq/log/:/var/log/rabbitmq
      - ./cert/:/cert/
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
      args:
        buildno: 1

